office-js/custom-functions.schema.json
Add new `id` field and make it required
=> Custom Functions: include new `id` field

office-js/custom-functions.schema.json
1. Add Any type
2. Set defaults to type: any. No longer require type.
3. Set dimensionality default to: "scalar"
4. Add optional parameter
5. Add requiresAddress for the caller.address api
6. Update description with a link to the documentation
=> Update schema with additional metadata

rush/v5/command-line.schema.json, rush/v5/rush.schema.json
Merge master => live to bring over the CF changes that @keyur32  made.
=> Merge master => live

office-js/custom-functions.schema.json
=> Remove unneeded comma

sp/v2/view-formatting.schema.json, sp/view-formatting.schema.json
- Added tileProps to the schema
- Update description for existing properties
- Fixed $ref for formatter to point to relevant version
=> Update view formatting schema to include tileProps

sp/column-formatting.schema.json, sp/v2/column-formatting.schema.json
Updated schema with new features.
=> Added defaultHoverField and customCardProps

teams/v1.6/MicrosoftTeams.Localization.schema.json, teams/v1.6/MicrosoftTeams.schema.json
=> teams schema v1.6

sp/v2/column-formatting.schema.json, sp/v2/row-formatting.schema.json, sp/v2/tile-formatting.schema.json, sp/v2/view-formatting.schema.json
This update contains the following 2 changes - 
1. Column formatting schema update based on SharePoint/sp-dev-docs#6206 to formatting docs.
2. Break down View formatting schema into smaller schema files.
=> Custom formatting docs update

sp/v2/column-formatting.schema.json
This update contains the following 2 changes -
1. Added ` viewBox` and `preserveAspectRatio` attributes
2. Added `columnFormatterReference`
=> Update column formatting schema

sp/v2/column-formatting.schema.json, sp/v2/row-formatting.schema.json, sp/v2/tile-formatting.schema.json
Update formatter schema for column and view formatting. Added -
1. New action `openContextMenu`
2. Group header formatter support for List and Gallery View
3. Group and list footer formatter support for List View
4. Hide group and list footer support for List View
=> Update formatting schema 

teams/v.1.10/MicrosoftTeams.Localization.schema.json, teams/v.1.10/MicrosoftTeams.schema.json
=> added manifest version 1.10

sp/v2/column-formatting.schema.json, sp/v2/row-formatting.schema.json, sp/v2/tile-formatting.schema.json
Changes in the update -
1. Fixed reference bug in column-formatting schema that showed an [error in VS2019](https://developercommunity.visualstudio.com/t/Issue-with-SharePoint-JSON-Schema-in-Vis/1503628)
2. Added some defaults for improved authoring experience
=> Add defaults and fix reference bug

sp/v2/board-formatting.schema.json, sp/v2/view-formatting.schema.json
Changes in this update -
1. Add schema for board view JSON customization
2. Add kanbanProps reference to view formatter JSON schema
=> Add board view props

spfx-build/package-solution.schema.json
Updates SPFx package-solution.schema.json with new properties: appId and replyUrl
=> appId and replyUrl in package-solution schema

sp/v2/calendar-formatting.schema.json, sp/v2/column-formatting.schema.json, sp/v2/view-formatting.schema.json
Changes in this update -
1. Add `additionalEventClass` prop for Calendar `monthProps`
2. Add `draggable` attribute
3. Add `p` elmType
=> Formatter schema update August 2022

rush/v5/command-line.schema.json
Make a trivial change to see if the CDN deployment is now working correctly.
See https://github.com/microsoft/json-schemas/issues/116#issuecomment-1447534159 for details.
=> Test to see whether deployment has been fixed

rush/v5/command-line.schema.json
=> Another test to see whether deployment has been fixed

teams-toolkit/teamsapp-yaml/v1.3/yaml.schema.json
feat: release Teams Toolkit yaml schema version: v1.3
=> feat: teams toolkit yaml schema v1.3

heft/v0/heft-jest-plugin.schema.json, heft/v0/storybook.schema.json, rush/v5/experiments.schema.json, rush/v5/pnpm-config.schema.json, rush/v5/rush.schema.json, rush/v5/subspaces.schema.json, rush/v5/version-policies.schema.json
- Add schemas from Heft 0.64.3
- Add schemas from Rush 5.113.1
This includes the experimental new **subspaces.schema.json** file.
@william2958 @iclanton
=> Update Rush and Heft schemas

teams-toolkit/teamsapp-yaml/v1.4/yaml.schema.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26964629
=> feat: teams toolkit yaml schema v1.4

dotnet/target-framework-moniker.schema.json
Authored based off [Microsoft Docs](https://learn.microsoft.com/en-us/dotnet/standard/frameworks)
=> Create .NET TFM json schema 

fabric/item/report/definition/page/1.0.0/schema.json
Add field expression back to page binding - page schema
=> Fabric - add field expression back to page schema

fabric/item/report/definition/page/1.0.0/schema.json
Add field expression back to fabric page schema for page binding
=> Fabric - add field expression back to page schema - live

teams-toolkit/teamsapp-yaml/v1.5/yaml.schema.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28013335
=> feat: teams toolkit yaml schema v1.5

teams/v1.17/MicrosoftTeams.schema.json
Added all 4 possible values to the scopes enum under requirementsExtensionElement, modified minimum and maximum number of elements in the scopes list.
=> Modify scopes under requirementsExtensionElement

rush/v5/common-versions.schema.json, rush/v5/deploy-scenario.schema.json, rush/v5/experiments.schema.json, rush/v5/repo-state.schema.json, rush/v5/rush-alerts.schema.json, rush/v5/rush.schema.json
Includes the new `rush-alerts.json` schema from PR https://github.com/microsoft/rushstack/pull/4801
CC @g-chao
=> Update JSON schemas for Rush 5.130.0

api-extractor/v7/api-extractor.schema.json, rush/v5/experiments.schema.json
=> Update Rush Stack schemas

teams/vDevPreview/MicrosoftTeams.schema.json
- OE Spam
- Remove required property
=> Add OE spam schema changes

teams/vDevPreview/MicrosoftTeams.schema.json
Add copilot agents to devpreview schema
=> Add copilot extensions to devpreview schema

teams-toolkit/teamsapp-yaml/v1.6/yaml.schema.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29450429
=> feat: teamsapp yaml schema v1.6

teams/v1.19/MicrosoftTeams.Localization.schema.json, teams/v1.19/MicrosoftTeams.ResponseRenderingTemplate.schema.json, teams/v1.19/MicrosoftTeams.schema.json, teams/vDevPreview/MicrosoftTeams.Localization.schema.json, teams/vDevPreview/MicrosoftTeams.schema.json
This change adds v1.19 app schema version.
=> [In review] Introduce v1.19 and update devpreview schemas

teams-toolkit/teamsapp-yaml/v1.7/yaml.schema.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30667310
=> feat: teams toolkit yaml schema v1.7

fabric/item/report/definition/filterConfiguration/1.0.0/schema-embedded.json, fabric/item/report/definition/visualConfiguration/1.5.0/schema-embedded.json
Aligning the `$id` for embedded filter and visual configuration schemas to their `$ref` values in other schemas.
=> [Report Definition] 24.12 schema quick fix

fabric/item/orgapp/definition/orgAppDefinition/1.0.0/schema.json
=> Create schema for Org App artifacts

fabric/item/orgapp/definition/orgAppDefinition/1.0.0/schema.json, spfx/client-side-component-manifest.schema.json, spfx/prefab-app-manifest.schema.json
add PREFAB component type for SPFx
=> add PREFAB component type for SPFx

fabric/item/orgapp/definition/orgAppDefinition/1.0.0/schema.json
Remove minLength constraint on OverviewHeader.body
=> Org app schema: Remove min size constraint for overview body

spfx/client-side-web-part-manifest.schema.json
Update on the web part schema for trying to trigger publishing process.
=> Client-side web part schema change to trigger publishing

spfx/client-side-web-part-manifest.schema.json
Trying to trigger publishing of the latest schema version
=> Publishing latest updates

teams/v1.20/MicrosoftTeams.schema.json
Add definition for elementReference, MutualDependency and onewaydependency
=> Add Definition for elementReference and Dependencies

fabric/item/metricSet/definition/metricSet/1.0.0/schema.json, fabric/item/metricSet/definition/semanticModel/1.0.0/schema.json
Schema for Metric Set artifacts.
=> Create schemas for MetricSet artifact and SemanticModel

teams/vDevPreview/MicrosoftTeams.Localization.schema.json, teams/vDevPreview/MicrosoftTeams.schema.json
Public Preview changes for Feb 2025
=> Public Preview changes

teams/v1.20/MicrosoftTeams.schema.json
Fix manifest version for GA 1.20
=> Fix GA 1.20 manifest version

teams/v1.20/MicrosoftTeams.schema.json
=> Add CEA description update

teams/vDevPreview/MicrosoftTeams.schema.json
=> Fix background load config

fabric/gitIntegration/platformProperties/2.1.0/schema.json
added a new property to the json, resulting in a version bump
=> updatedschema.json to 2.1.0

fabric/item/mirroredAzureDatabricksCatalog/definition/mirroredAzureDatabricksCatalogDefinition/1.0.0/schema.json
Added Schema for Mirrored Azure Databricks Catalog Definition Contract
=> Add Schema Definition for Mirrored ADB Artifact

teams-toolkit/teamsapp-yaml/v1.8/yaml.schema.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/32599432
=> feat: teamsapp-yaml v1.8

fabric/item/report/definitionProperties/1.0.0/schema.json, fabric/item/report/localSettings/1.0.0/schema.json, fabric/item/semanticModel/definitionProperties/1.0.0/schema.json, fabric/item/semanticModel/editorSettings/1.0.0/schema.json, fabric/item/semanticModel/localSettings/1.1.0/schema.json, fabric/item/semanticModel/modelReference/2.0.0/schema.json, fabric/item/semanticModel/unappliedChanges/1.0.0/schema.json, fabric/pbip/pbipProperties/1.0.0/schema.json
We are changing file format in all files of the PBIP project. Now all files will have mandatory schema property pointing to the schema documents. This change publishes the schema documents for each of the PBIP files.
=> Schema files for PBIP version 2.

.github/workflows/validate-schemas.yml, fabric/item/report/definition/report/1.3.0/schema.json, tests/validate-schemas_test.py
=> Test schema JSON and $refs are valid

teams/vDevPreview/MicrosoftTeams.Localization.schema.json, teams/vDevPreview/MicrosoftTeams.schema.json
Reverts microsoft/json-schemas#356
=> Revert "Main to live"

fabric/item/orgapp/definition/orgAppDefinition/2.0.0/schema.json
Copied the V1 schema. The only changes you can find by looking for nodes with AudienceSettings and the 2.0.0 in the schema URL.
=> Add OrgApp V2 version for future when we want to publish to public.

copilot/declarative-agent/v1.4/schema.json
=> DeclarativeAgents: Add schema v1.4 of the DA Manifest

copilot/plugin/v2.3/schema.json
=> DeclarativeAgents(Plugin): Add v2.3 version of Plugin schema.

teams-toolkit/teamsapp-yaml/v1.8/yaml.schema.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33156486
=> feat: update the v1.8 schema

teams-toolkit/teamsapp-yaml/v1.9/yaml.schema.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33156486
=> feat: update the version to 1.9

fabric/item/report/definitionProperties/1.0.0/schema.json, fabric/item/report/definitionProperties/2.0.0/schema.json
We are adding new format for report's dataset reference by connection.
=> New version 2.0 of report dataset reference by connection.

copilot/declarative-agent/v1.4/schema.json
This PR adds `Disclaimer` object to Declarative Agent manifest schema 1.4.
Fixes https://github.com/microsoft/Microsoft.Plugins.Manifest/issues/619
=> feat: Add Disclaimer to DA Schema 1.4

fabric/item/schemaSet/definition/1.0.0/schema.json
Adding schema json for schemaSet.
=> Adding schema json for schemaSet.

copilot/declarative-agent/v1.5/schema.json
This PR adds the JSON Schema for Copilot Declarative Agent Manifest v1.5.
Ports the changes made in #397 to live.
=> feat: Adds Copilot DA 1.5 schema. Port of 397

fabric/item/schemaSet/definition/1.0.0/schema.json
Adding schemaSetDefinition to Live Branch.
=> Adding schemaSetDefinition to Live Branch.

fabric/item/eventSchemaSet/definition/1.0.0/schema.json
Updating schemaSet name  to be eventSchemaSet.
=> Updating schemaSet to be eventSchemaSet.

fabric/item/dataAgent/definition/dataAgent/2.1.0/schema.json, fabric/item/dataAgent/definition/dataSource/1.0.0/schema.json, fabric/item/dataAgent/definition/fewShots/1.0.0/schema.json, fabric/item/dataAgent/definition/publishInfo/1.0.0/schema.json, fabric/item/dataAgent/definition/stageConfiguration/1.0.0/schema.json
This PR contains the schema of the Data Agent artifact in Microsoft Fabric, to be used in git/deployment pipelines
=> Microsoft Fabric Data Agent artifact CICD schema

fabric/item/map/definition/1.0.0/schema.json
Adding the Map definition version as documented in https://review.learn.microsoft.com/en-us/rest/api/fabric/articles/item-management/definitions/map-definition?branch=users%2Fismaelna%2Fadd-map-to-mappingjs
=> Add Map Definition
