microsoft/json-schemas

teams/v1.3/MicrosoftTeams.schema.json
Removing the webApplicationInfo section because it is not available in the Teams client.
=> Final revision of the 1.3 schema

office-js/custom-functions.schema.json
* Add missing "helpUrl" and "parameter.description" properties from schema.
* Remove no-longer-used "sync" option
* Make schema stricter by adding `"additionalProperties": false` to each object type.
=> Update Custom Functions schema

rush/v5/rush.schema.json, rush/v5/version-policies.schema.json
Fixes https://github.com/Microsoft/web-build-tools/issues/1182
=> Update JSON schemas based on Rush 5.6.3

office-js/custom-functions.schema.json
Result type is no longer supported. By default Excel will coerce these as appropriate.
Please HOLD merging this PR until the March Build is ready and deployed to Insider Fast.
=> In the March Insiders Build: update result

office-js/custom-functions.schema.json
Call this out in JSON so developers see it in autocomplete context.
=> Add note to call out limitation cases in json

sp/v2/column-formatting.schema.json
Changes in the update -
1. Support `inlineEditField`
2. Add `setValue` action and `actionInput`
=> Add inlineEditField and setValue action in column-formatter schema

lockfile-explorer/lockfile-lint.schema.json
Add the JSON Schema from https://github.com/microsoft/rushstack/pull/4779
=> Add lockfile-lint.schema.json

teams-toolkit/teamsapptesttool-config/0.1.0/config.schema.json
This is the schema for Teams App Test Tool configuration file in Teams Toolkit. It is used for Intellisense in vscode.
Its documentation is at https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-your-teams-app-test-tool?tabs=vscode%2Cclijs#default-configuration
Previously it is hosted on a public Azure Blob which is not secure. As Teams Toolkit yaml schema is moved here, both for consistency and security, we should move Test Tool's schema here.
Nothing of the schema file content is changed. Just plain copy.
=> Add teams app test tool config schema

fabric/item/report/definition/visualContainer/CHANGELOG.md
As requested by @michaeldfaber, add more detail to the visual-specific changes contained in the November PBI Desktop release that prompted the version bump to 1.4.0.
=> Update fabric-report-visualContainer 1.4.0 changelog with more details

fabric/item/report/definition/filterConfiguration/1.0.0/schema-embedded.json, fabric/item/report/definition/visualConfiguration/1.5.0/schema-embedded.json
Aligning the `$id` for embedded filter and visual configuration schemas to their `$ref` values in other schemas.
=> [Report Definition] 24.12 schema quick fix

fabric/item/orgapp/definition/orgAppDefinition/1.0.0/schema.json
There is no min size constraint for overview item's body.
=> Org app schema: Remove min size constraint for overview body

fabric/item/userDataFunction/definition/1.1.0/schema.json, fabric/item/userDataFunction/definition/CHANGELOG.md
Fabric User Data Functions recently added private libraries to their python functions. This change updates the item schema to include private libraries
=> Update UserDataFunctions schema to include private libraries

.github/workflows/auto-create-manifest-schema-release-pr.yml
The GitHub worklow described below aims to automate the process of releasing Microsoft 365 app manifest schemas.
STEPS:
- It only is triggered when pushes are made to the repo folder teams.
- It creates a PR from the working branch to main.
- It checks for completion and then creates a PR from main to live.
=> Automate Microsoft 365 app manifest schema release

copilot/declarative-agent/v1.4/schema.json
This PR removes `sensitivity_label` from the DeclarativeAgents manifest 1.4 as it is currently not supported by the platform team.
=> DeclarativeAgents: Remove sensitivity_label from DA manifest 1.4

copilot/declarative-agent/v1.4/schema.json
Port of #377.
This PR removes sensitivity_label from the DeclarativeAgents manifest 1.4 as the platform team does currently not support it.
=> DeclarativeAgents - Live: Remove sensitivity_label from DA manifest 1.4

copilot/declarative-agent/v1.4/schema.json
This PR removes disclaimer from the DeclarativeAgents manifest 1.4 as the platform team does currently not support it.
Fixes https://github.com/microsoft/Microsoft.Plugins.Manifest/issues/605
=> DeclarativeAgents: Remove Disclaimer from DA Manifest v1.4

copilot/declarative-agent/v1.4/schema.json
Port of #379.
This PR removes disclaimer from the DeclarativeAgents manifest 1.4 as the platform team does currently not support it.
Fixes https://github.com/microsoft/Microsoft.Plugins.Manifest/issues/605
=> DeclarativeAgents - Live: Remove Disclaimer from DA Manifest v1.4

fabric/item/report/definitionProperties/2.0.0/schema.json
Version 2.0.0 removes several properties from byConnection object and leaves just the connection string.
=> Version 2.0.0 for PBIR reflecting connection properties

fabric/gitIntegration/schedules/1.0.0/schema.json
This PR adds schema used by fabric Git integration on item schedules in Git repositories
=> Add fabirc scheduler cicd schema

copilot/declarative-agent/v1.6/schema.json
Ports the changes made in #415.
This PR addas DA v1.6 JSON schema with the following changes per the schema diff at https://spec-hub.azurewebsites.net/diff?oldUrl=/specifications/DAManifest-1.5.html&newUrl=/specifications/DAManifest-draft.html:
Adds:
- `sensitivity_label` to the DA.
- `EmbeddedKnowledge` capability to the DA.
=> feat: Add DA Schema v1.6.

fabric/item/operationsAgents/definition/1.0.0/schema.json
This JSON schema defines the structure for an Operations Agent, including its configuration, playbook, and required properties.
=> Add JSON schema for Operations Agent definition

copilot/declarative-agent/v1.6/schema.json
This PR updates the DA 1.6 JSON Schema by proposing the following changes:
- Increases conversation_starters limit from 6 to 12.
- Updates the `embedded_resource_snapshot_id` and embedded knowledge `file` regex by removing double-escaped brackets `\\\\]\\\\]` which created "lone quantifier brackets" that are invalid in regex.
Fixes https://github.com/microsoft/Microsoft.Plugins.Manifest/issues/686
Fixes https://github.com/microsoft/Microsoft.Plugins.Manifest/issues/685
=> fix: Update DA 1.6 JSON Schema
